// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserManagement.Data;

#nullable disable

namespace UserManagement.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserManagement.Data.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("Forename")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DateOfBirth = new DateOnly(1978, 4, 12),
                            Email = "ploew@example.com",
                            Forename = "Peter",
                            IsActive = true,
                            NormalizedEmail = "PLOEW@EXAMPLE.COM",
                            Surname = "Loew"
                        },
                        new
                        {
                            Id = 2L,
                            DateOfBirth = new DateOnly(1965, 10, 28),
                            Email = "bfgates@example.com",
                            Forename = "Benjamin Franklin",
                            IsActive = true,
                            NormalizedEmail = "BFGATES@EXAMPLE.COM",
                            Surname = "Gates"
                        },
                        new
                        {
                            Id = 3L,
                            DateOfBirth = new DateOnly(1989, 2, 7),
                            Email = "ctroy@example.com",
                            Forename = "Castor",
                            IsActive = false,
                            NormalizedEmail = "CTROY@EXAMPLE.COM",
                            Surname = "Troy"
                        },
                        new
                        {
                            Id = 4L,
                            DateOfBirth = new DateOnly(1972, 8, 19),
                            Email = "mraines@example.com",
                            Forename = "Memphis",
                            IsActive = true,
                            NormalizedEmail = "MRAINES@EXAMPLE.COM",
                            Surname = "Raines"
                        },
                        new
                        {
                            Id = 5L,
                            DateOfBirth = new DateOnly(1958, 12, 3),
                            Email = "sgodspeed@example.com",
                            Forename = "Stanley",
                            IsActive = true,
                            NormalizedEmail = "SGODSPEED@EXAMPLE.COM",
                            Surname = "Goodspeed"
                        },
                        new
                        {
                            Id = 6L,
                            DateOfBirth = new DateOnly(1981, 6, 25),
                            Email = "himcdunnough@example.com",
                            Forename = "H.I.",
                            IsActive = true,
                            NormalizedEmail = "HIMCDUNNOUGH@EXAMPLE.COM",
                            Surname = "McDunnough"
                        },
                        new
                        {
                            Id = 7L,
                            DateOfBirth = new DateOnly(1992, 1, 16),
                            Email = "cpoe@example.com",
                            Forename = "Cameron",
                            IsActive = false,
                            NormalizedEmail = "CPOE@EXAMPLE.COM",
                            Surname = "Poe"
                        },
                        new
                        {
                            Id = 8L,
                            DateOfBirth = new DateOnly(1986, 9, 30),
                            Email = "emalus@example.com",
                            Forename = "Edward",
                            IsActive = false,
                            NormalizedEmail = "EMALUS@EXAMPLE.COM",
                            Surname = "Malus"
                        },
                        new
                        {
                            Id = 9L,
                            DateOfBirth = new DateOnly(1975, 3, 21),
                            Email = "dmacready@example.com",
                            Forename = "Damon",
                            IsActive = false,
                            NormalizedEmail = "DMACREADY@EXAMPLE.COM",
                            Surname = "Macready"
                        },
                        new
                        {
                            Id = 10L,
                            DateOfBirth = new DateOnly(1990, 11, 8),
                            Email = "jblaze@example.com",
                            Forename = "Johnny",
                            IsActive = true,
                            NormalizedEmail = "JBLAZE@EXAMPLE.COM",
                            Surname = "Blaze"
                        },
                        new
                        {
                            Id = 11L,
                            DateOfBirth = new DateOnly(1983, 7, 14),
                            Email = "rfeld@example.com",
                            Forename = "Robin",
                            IsActive = true,
                            NormalizedEmail = "RFELD@EXAMPLE.COM",
                            Surname = "Feld"
                        });
                });

            modelBuilder.Entity("UserManagement.Data.Entities.UserActionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("UserActionLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
